name: v$(SemVer)

variables:
  Ver: '0.9.0'
  BuildRev: $[counter(variables.Ver, 1)]
  BuildVer: $[ format('{0}.{1}', variables.Ver, variables.BuildRev) ]
  SemVer: $[ format('{0}-pre{1}', variables.Ver, variables.BuildRev) ]
  ${{ if eq( variables.Build.SourceBranchName, 'master' ) }}:
    SemVer: '0.10.0'

trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: windows-2019

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "SemVer: $(SemVer)"
      Write-Host "IsFork: $env:SYSTEM_PULLREQUREST_ISFORK"
      Write-Host "PullRequestId: $env:SYSTEM_PULLREQUEST_PULLREQUESTID"
      Write-Host "PullRequestNumber: $env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER"
      Write-Host "SourceBranchName: $(Build.SourceBranchName)"