name: $(SemVer)

variables:
  BuildRev: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  SemVer: $[format('{0:yyyy}.{0:MM}.{0:dd}-pre{1}', pipeline.startTime, variables.BuildRev)]
  CommitId: $(Build.SourceVersion)
  BuildConfiguration: Release

trigger:
  batch: true
  branches:
    include:
    - master

pr:
  autoCancel: true
  branches:
    include:
    - master

pool:
  vmImage: ubuntu-18.04

stages:
- stage: Build
  jobs:
  - job: BuildTest
    displayName: 'Build & test'
    timeoutInMinutes: 5
    cancelTimeoutInMinutes: 2
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core 3.1.x'
      inputs:
        version: '3.1.x'
        packageType: sdk

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: build
        projects: 'BomSample/BomSample.csproj'
        arguments: '-c $(BuildConfiguration) --no-incremental --nologo -p:TreatWarningsAsErrors=true -p:Version=$(SemVer) -p:InformationalVersion=$(CommitId)'

    - task: DotNetCoreCLI@2
      displayName: 'Test'
      inputs:
        command: test
        projects: 'BomSample/BomSample.csproj'
        arguments: '-c $(BuildConfiguration) --no-build'
        testRunTitle: 'UnitTests'
